---
- name: apt commands
  hosts: nano
  remote_user: ustc

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
    become: yes

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
    become: yes
  
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
    become: yes

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
    become: yes