- name: leaf nodes
  hosts: kube_node
  tasks: 
  # - name: leaf nodes
  #   command: microk8s.join 192.168.1.10:25000/cf3abe8553fb2fdb0b01b472d43cb665/acb04b72c438
  #   become: yes

  - name: microk8s leave
    command: microk8s leave
    when: false
    become: yes

  - name: snap remove
    command: snap remove {{item}}
    loop:
    - microk8s
    - core18
    become: yes