---
- name: k8s Deploy
  hosts: T640

  tasks:

  - name: Creates directory
    file:
      path: Kubeedge
      state: directory

  - name: Kubeedge
    ansible.builtin.shell: |
      wget https://download.fastgit.org/kubeedge/kubeedge/releases/download/v1.7.1/keadm-v1.7.1-linux-amd64.tar.gz
      wget https://download.fastgit.org/kubeedge/kubeedge/releases/download/v1.7.1/kubeedge-v1.7.1-linux-amd64.tar.gz
    args: 
      chdir: Kubeedge
  #     kubeadm init --control-plane-endpoint=cluster-endpoint
  #   become: yes


  # - name: kubespray
  #   shell: |
  #     conda create -n kubespray -y pip3
  #     conda activate kubespray
  #     pip3 install -r requirements.txt
  #     cp -rfp inventory/sample inventory/mycluster
  #     declare -a IPS=(10.10.1.3 10.10.1.4 10.10.1.5)
  #     CONFIG_FILE=inventory/mycluster/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}
      

  # - name: kubespray uninstall
  #   shell: |
  #     conda deactivate kubespray
  #     conda env remove -n kubespray

  #     ansible-playbook -i inventory/mycluster/inventory.ini cluster.yml

  # - name: Initializing your control-plane node
    # community.general.shell:
    #   sudo apt install conntrack
    #   sudo swapoff -a